processes:

  0-health:
    command: ./scripts/pethub-health.sh

  1-postgresql:
    command: docker compose up postgresql
  
  2-pethub-web:
    command: ./scripts/pethub-web-start.sh

  3-nginx:
    command: docker compose up nginx
